package ramka;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.security.Key;
import java.text.ParseException;

import static java.lang.Thread.sleep;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hanus_junior
 */
public class NewJFrame extends javax.swing.JFrame  {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textField = new javax.swing.JTextField();
        butt7 = new javax.swing.JButton();
        butt8 = new javax.swing.JButton();
        butt9 = new javax.swing.JButton();
        butt4 = new javax.swing.JButton();
        butt5 = new javax.swing.JButton();
        butt6 = new javax.swing.JButton();
        butt1 = new javax.swing.JButton();
        butt2 = new javax.swing.JButton();
        butt3 = new javax.swing.JButton();
        butt0 = new javax.swing.JButton();
        butDot = new javax.swing.JButton();
        butRes = new javax.swing.JButton();
        butDivision = new javax.swing.JButton();
        butMultiply = new javax.swing.JButton();
        buttSubtract = new javax.swing.JButton();
        buttSum = new javax.swing.JButton();
        textField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if(!goodCharacter2(e.getKeyChar()))
                e.consume();
            }

            @Override
            public void keyPressed(KeyEvent e) {
                //lock unexpected text
                if(e.isControlDown() &&  e.getKeyCode() == KeyEvent.VK_V ){
                    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                    DataFlavor flavor = DataFlavor.stringFlavor;
                    String cubby ="", text ="";
                    int countDots = 0, countOperation = 0;

                    try{
                        cubby = (String)clipboard.getData(flavor);
                    }
                    catch(UnsupportedFlavorException ex){
                        System.out.println(ex.getMessage());
                    }
                    catch (IOException ex){
                        System.out.println(ex.getMessage());
                    }
                    text = textField.getText()+cubby;
                    for(int i = 0; i < cubby.length(); i++){
                        if(!goodCharacter2(cubby.charAt(i)) ){
                            e.consume();
                            System.out.println("0");
                            break;
                        }
                    }
                    for(int i = 0; i < text.length() ; i++ ){
                        if(text.charAt(i) < '0' && text.charAt(i) != '.')
                            countOperation++;
                        if(countOperation>1){
                            e.consume();
                            System.out.println("1");
                            break;
                        }

                        if(text.charAt(i) == '.' && text.charAt(i-1) < '0' && i > 0){
                            e.consume();
                            System.out.println("3");
                            break;
                        }
                        if(text.charAt(i) =='.'){
                            countDots++;
                            System.out.println("4 " + countDots);
                        }
                        if(countDots>1){
                            System.out.println("5");
                            e.consume();
                            break;
                        }
                        if(goodCharacter2(text.charAt(i)) && text.charAt(i) != '.' && text.charAt(i) <'0')
                            countDots = 0;
                    }
                }
                else if(e.getKeyCode() == KeyEvent.VK_ENTER || e.getKeyChar() == '=')
                    textField.setText( getResult());

                textField.setText(errorReact());
            }
        });
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 0, 240));

        textField.setColumns(15);
        textField.setMaximumSize(new Dimension(50,40));
        jScrollPane1.setViewportView(textField);

        butt0.addActionListener(new buttonHandler());
        butt1.addActionListener(new buttonHandler());
        butt2.addActionListener(new buttonHandler());
        butt3.addActionListener(new buttonHandler());
        butt4.addActionListener(new buttonHandler());
        butt5.addActionListener(new buttonHandler());
        butt6.addActionListener(new buttonHandler());
        butt7.addActionListener(new buttonHandler());
        butt8.addActionListener(new buttonHandler());
        butt9.addActionListener(new buttonHandler());
        butDot.addActionListener(new buttonHandler());
        butMultiply.addActionListener(new buttonHandler());
        butRes.addActionListener(new buttonHandler());
        butDivision.addActionListener(new buttonHandler());
        buttSubtract.addActionListener(new buttonHandler());
        buttSum.addActionListener(new buttonHandler());

        textField.setFont(new Font("mono",Font.BOLD ,20) );


        butt4.setText("4");

        butt5.setText("5");

        butt6.setText("6");


        butt7.setText("7");

        butt8.setText("8");

        butt9.setText("9");

        butt1.setText("1");

        butt2.setText("2");

        butt3.setText("3");

        butt0.setText("0");

        butDot.setText(".");

        butRes.setText("=");

        butDivision.setText("/");

        butMultiply.setText("*");

        buttSubtract.setText("-");

        buttSum.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(butt0, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                        .addComponent(butt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(butt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(butt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(butDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(butt2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                        .addComponent(butt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(butt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(butt9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(butt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(butRes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                        .addComponent(butt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(buttSum, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                        .addComponent(buttSubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(butDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(butMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(butt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butt9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(butt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(butt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttSubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(buttSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(butRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(butt0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(butDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>

    class buttonHandler implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource().equals(butt0))
                textField.setText(textField.getText() + '0');
            if(e.getSource().equals(butt1))
                textField.setText(textField.getText()+ 1);
            if(e.getSource().equals(butt2))
                textField.setText(textField.getText()+ 2);
            if(e.getSource().equals(butt3))
                textField.setText(textField.getText()+ 3);
            if(e.getSource().equals(butt4))
                textField.setText(textField.getText()+ 4);
            if(e.getSource().equals(butt5))
                textField.setText(textField.getText()+ 5);
            if(e.getSource().equals(butt6))
                textField.setText(textField.getText()+ 6);
            if(e.getSource().equals(butt7))
                textField.setText(textField.getText()+ 7);
            if(e.getSource().equals(butt8))
                textField.setText(textField.getText()+ 8);
            if(e.getSource().equals(butt9))
                textField.setText(textField.getText()+ 9);
            if(e.getSource().equals(butDot))
                textField.setText(textField.getText()+ ".");
            if(e.getSource().equals(butDivision))
                textField.setText(textField.getText()+ "/");
            if(e.getSource().equals(butMultiply))
                textField.setText(textField.getText()+ "*");
            if(e.getSource().equals(buttSubtract))
                textField.setText(textField.getText()+ "-");
            if(e.getSource().equals(buttSum))
                textField.setText(textField.getText()+ "+");
            if(e.getSource().equals(butRes))
                textField.setText( getResult());
            if(true)
                textField.setText(errorReact());
        }
    }
    public boolean goodCharacter(char c){ //return 1 if char is number
        if(c > '9' || c < '0')
            return false;
        return true;
    }
    public boolean goodCharacter2(char c){
        if((c > '9' || c < '0') && c !='.' && c != '-' && c != '+' && c != '/' && c != '*')
            return false;
        return true;
    }
    private int dots = 0;
    private int operators = 0;
    public String errorReact(){
        String text = textField.getText();
        int i = text.length();
        for(int m = 0; m < i; m++){

        }


        return text;
    }
    public String getResult(){
        String text = textField.getText();
        System.out.println(text.length());
        int i = 0;
        String a ,b="0" ;
        while((goodCharacter(text.charAt(i)) || text.charAt(i) == '.') && i<text.length()-1){
            i++;

            System.out.println(i );
        }
        if(i == text.length()-1 || (i == text.length() && text.charAt(i-1)>='0'))
            return text.substring(0,i+1);
        a = text.substring(0, i);
        b = text.substring(i+1,text.length());

        double x = Double.parseDouble(a);
        double y = Double.parseDouble(b);
        if(text.charAt(i)=='+')
            return Double.toString(x+y);
        if(text.charAt(i)=='-')
            return Double.toString(x-y);
        if(text.charAt(i)=='*')
            return Double.toString(x*y);
        if(text.charAt(i)=='/' && y!= 0.0)
            return Double.toString(x/y);
        if(text.charAt(i)=='/' && y==0.0)
            textField.setText("Zakazane działanie");
        try {
                sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

        return "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java   ".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    private javax.swing.JButton butDivision;
    private javax.swing.JButton butDot;
    private javax.swing.JButton butMultiply;
    private javax.swing.JButton butRes;
    private javax.swing.JButton butt0;
    private javax.swing.JButton butt1;
    private javax.swing.JButton butt2;
    private javax.swing.JButton butt3;
    private javax.swing.JButton butt4;
    private javax.swing.JButton butt5;
    private javax.swing.JButton butt6;
    private javax.swing.JButton butt7;
    private javax.swing.JButton butt8;
    private javax.swing.JButton butt9;
    private javax.swing.JButton buttSubtract;
    private javax.swing.JButton buttSum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textField;
}
